import type { SeedExam } from '../types'

/**
 * KPSS Lisans — Genel Yetenek / Genel Kültür oturumu.
 *
 * Yapı ÖSYM'nin yayımladığı konu dağılımına ve MEB ortaöğretim programına
 * dayanır. Bu dosya yalnızca müfredat ağacını (ders → ünite → konu) taşır;
 * kazanım, video, soru ve kart içerikleri ayrı bir içerik dosyasında
 * `slug` üzerinden bağlanır.
 */
export const kpssExam: SeedExam = {
  code: 'KPSS_LISANS',
  name: 'KPSS Lisans (Genel Yetenek - Genel Kültür)',
  description:
    'Kamu Personel Seçme Sınavı lisans düzeyi Genel Yetenek - Genel Kültür oturumu. Genel Yetenek bölümünde 30 Türkçe ve 30 Matematik, Genel Kültür bölümünde 27 Tarih, 18 Coğrafya, 9 Vatandaşlık ve 6 Güncel Bilgiler sorusu yer alır. Toplam 120 soru, 130 dakika; dört yanlış bir doğruyu götürür.',
  wrongPenaltyDivisor: 4,
  defaultExamDate: '2027-09-12',
  totalQuestions: 120,
  durationMinutes: 130,
  orderIndex: 3,
  subjects: [
    // =====================================================================
    // TÜRKÇE — 30 soru
    // =====================================================================
    {
      name: 'Türkçe',
      slug: 'turkce',
      orderIndex: 0,
      color: '0 72% 55%',
      questionCount: 30,
      units: [
        {
          name: 'Sözcükte Anlam',
          slug: 'sozcukte-anlam',
          orderIndex: 0,
          topics: [
            {
              title: 'Gerçek, Mecaz ve Terim Anlam',
              slug: 'gercek-mecaz-ve-terim-anlam',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sözcükler Arası Anlam İlişkileri',
              slug: 'sozcukler-arasi-anlam-iliskileri',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Deyimler ve Atasözleri',
              slug: 'deyimler-ve-atasozleri',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sözcükte Anlam Olayları',
              slug: 'sozcukte-anlam-olaylari',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Somut-Soyut ve Genel-Özel Anlamlılık',
              slug: 'somut-soyut-ve-genel-ozel-anlamlilik',
              orderIndex: 4,
              estimatedMinutes: 20,
              difficulty: 2,
              examWeight: 0.4,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Cümlede Anlam',
          slug: 'cumlede-anlam',
          orderIndex: 1,
          topics: [
            {
              title: 'Cümlede Anlam İlişkileri',
              slug: 'cumlede-anlam-iliskileri',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cümle Yorumlama ve Kesin Yargı',
              slug: 'cumle-yorumlama-ve-kesin-yargi',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cümlede Anlatım Biçimleri ve Duygular',
              slug: 'cumlede-anlatim-bicimleri-ve-duygular',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cümle Tamamlama ve Cümle Oluşturma',
              slug: 'cumle-tamamlama-ve-cumle-olusturma',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Paragraf',
          slug: 'paragraf',
          orderIndex: 2,
          topics: [
            {
              title: 'Paragrafta Konu, Ana Düşünce ve Yardımcı Düşünce',
              slug: 'paragrafta-konu-ana-dusunce-ve-yardimci-dusunce',
              orderIndex: 0,
              estimatedMinutes: 60,
              difficulty: 3,
              examWeight: 0.9,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Paragrafta Yapı: Giriş, Gelişme, Sonuç',
              slug: 'paragrafta-yapi-giris-gelisme-sonuc',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Paragraf Tamamlama',
              slug: 'paragraf-tamamlama',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Anlatımın Akışını Bozan Cümle',
              slug: 'anlatimin-akisini-bozan-cumle',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Anlatım Biçimleri ve Düşünceyi Geliştirme Yolları',
              slug: 'anlatim-bicimleri-ve-dusunceyi-gelistirme-yollari',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Paragrafı İkiye Bölme ve Paragrafa Soru Sorma',
              slug: 'paragrafi-ikiye-bolme-ve-paragrafa-soru-sorma',
              orderIndex: 5,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Ses Bilgisi, Yazım ve Noktalama',
          slug: 'ses-bilgisi-yazim-ve-noktalama',
          orderIndex: 3,
          topics: [
            {
              title: 'Ses Bilgisi ve Ses Olayları',
              slug: 'ses-bilgisi-ve-ses-olaylari',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yazım Kuralları',
              slug: 'yazim-kurallari',
              orderIndex: 1,
              estimatedMinutes: 60,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Noktalama İşaretleri',
              slug: 'noktalama-isaretleri',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Sözcük Türleri ve Sözcük Yapısı',
          slug: 'sozcuk-turleri-ve-sozcuk-yapisi',
          orderIndex: 4,
          topics: [
            {
              title: 'Sözcükte Yapı: Kök, Yapım ve Çekim Ekleri',
              slug: 'sozcukte-yapi-kok-yapim-ve-cekim-ekleri',
              orderIndex: 0,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İsimler ve Sıfatlar',
              slug: 'isimler-ve-sifatlar',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Zamir, Zarf, Edat, Bağlaç ve Ünlem',
              slug: 'zamir-zarf-edat-baglac-ve-unlem',
              orderIndex: 2,
              estimatedMinutes: 65,
              difficulty: 4,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Fiiller: Kip, Kişi ve Anlam Kaymaları',
              slug: 'fiiller-kip-kisi-ve-anlam-kaymalari',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Fiilimsiler',
              slug: 'fiilimsiler',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Fiilde Çatı',
              slug: 'fiilde-cati',
              orderIndex: 5,
              estimatedMinutes: 30,
              difficulty: 4,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Cümle Bilgisi ve Anlatım Bozuklukları',
          slug: 'cumle-bilgisi-ve-anlatim-bozukluklari',
          orderIndex: 5,
          topics: [
            {
              title: 'Cümlenin Öğeleri',
              slug: 'cumlenin-ogeleri',
              orderIndex: 0,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cümle Türleri',
              slug: 'cumle-turleri',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Anlama Dayalı Anlatım Bozuklukları',
              slug: 'anlama-dayali-anlatim-bozukluklari',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yapıya Dayalı Anlatım Bozuklukları',
              slug: 'yapiya-dayali-anlatim-bozukluklari',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // MATEMATİK — 30 soru
    // =====================================================================
    {
      name: 'Matematik',
      slug: 'matematik',
      orderIndex: 1,
      color: '217 91% 60%',
      questionCount: 30,
      units: [
        {
          name: 'Temel Kavramlar ve Sayılar',
          slug: 'temel-kavramlar-ve-sayilar',
          orderIndex: 0,
          topics: [
            {
              title: 'Temel Kavramlar',
              slug: 'temel-kavramlar',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sayı Basamakları',
              slug: 'sayi-basamaklari',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Bölme ve Bölünebilme Kuralları',
              slug: 'bolme-ve-bolunebilme-kurallari',
              orderIndex: 2,
              estimatedMinutes: 50,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'EBOB - EKOK',
              slug: 'ebob-ekok',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Asal Çarpanlar ve Faktöriyel',
              slug: 'asal-carpanlar-ve-faktoriyel',
              orderIndex: 4,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.4,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Rasyonel Sayılar ve Ondalık Gösterim',
              slug: 'rasyonel-sayilar-ve-ondalik-gosterim',
              orderIndex: 5,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Cebir',
          slug: 'cebir',
          orderIndex: 1,
          topics: [
            {
              title: 'Birinci Dereceden Denklemler',
              slug: 'birinci-dereceden-denklemler',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Basit Eşitsizlikler',
              slug: 'basit-esitsizlikler',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Mutlak Değer',
              slug: 'mutlak-deger',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Üslü Sayılar',
              slug: 'uslu-sayilar',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Köklü Sayılar',
              slug: 'koklu-sayilar',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Çarpanlara Ayırma ve Özdeşlikler',
              slug: 'carpanlara-ayirma-ve-ozdeslikler',
              orderIndex: 5,
              estimatedMinutes: 55,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Oran ve Orantı',
              slug: 'oran-ve-oranti',
              orderIndex: 6,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Problemler',
          slug: 'problemler',
          orderIndex: 2,
          topics: [
            {
              title: 'Sayı ve Kesir Problemleri',
              slug: 'sayi-ve-kesir-problemleri',
              orderIndex: 0,
              estimatedMinutes: 60,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yaş Problemleri',
              slug: 'yas-problemleri',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İşçi ve Havuz Problemleri',
              slug: 'isci-ve-havuz-problemleri',
              orderIndex: 2,
              estimatedMinutes: 45,
              difficulty: 4,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Hareket ve Hız Problemleri',
              slug: 'hareket-ve-hiz-problemleri',
              orderIndex: 3,
              estimatedMinutes: 65,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yüzde, Kâr-Zarar ve Faiz Problemleri',
              slug: 'yuzde-kar-zarar-ve-faiz-problemleri',
              orderIndex: 4,
              estimatedMinutes: 65,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Karışım Problemleri',
              slug: 'karisim-problemleri',
              orderIndex: 5,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Grafik ve Tablo Problemleri',
              slug: 'grafik-ve-tablo-problemleri',
              orderIndex: 6,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Rutin Olmayan Problemler',
              slug: 'rutin-olmayan-problemler',
              orderIndex: 7,
              estimatedMinutes: 60,
              difficulty: 5,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Kümeler, Fonksiyonlar ve Sayma',
          slug: 'kumeler-fonksiyonlar-ve-sayma',
          orderIndex: 3,
          topics: [
            {
              title: 'Kümeler',
              slug: 'kumeler',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İşlem ve Modüler Aritmetik',
              slug: 'islem-ve-moduler-aritmetik',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Fonksiyonlar',
              slug: 'fonksiyonlar',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.4,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Permütasyon ve Kombinasyon',
              slug: 'permutasyon-ve-kombinasyon',
              orderIndex: 3,
              estimatedMinutes: 45,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Olasılık',
              slug: 'olasilik',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sayısal Mantık ve Sayı Dizileri',
              slug: 'sayisal-mantik-ve-sayi-dizileri',
              orderIndex: 5,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Geometri: Açılar ve Üçgenler',
          slug: 'geometri-acilar-ve-ucgenler',
          orderIndex: 4,
          topics: [
            {
              title: 'Doğruda ve Üçgende Açılar',
              slug: 'dogruda-ve-ucgende-acilar',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Dik Üçgen ve Pisagor Bağıntısı',
              slug: 'dik-ucgen-ve-pisagor-bagintisi',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Özel Üçgenler ve Trigonometrik Oranlar',
              slug: 'ozel-ucgenler-ve-trigonometrik-oranlar',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Açıortay, Kenarortay ve Üçgende Benzerlik',
              slug: 'aciortay-kenarortay-ve-ucgende-benzerlik',
              orderIndex: 3,
              estimatedMinutes: 45,
              difficulty: 4,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Üçgende Alan',
              slug: 'ucgende-alan',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Geometri: Çokgenler, Çember ve Katı Cisimler',
          slug: 'geometri-cokgenler-cember-ve-kati-cisimler',
          orderIndex: 5,
          topics: [
            {
              title: 'Çokgenler ve Dörtgenler',
              slug: 'cokgenler-ve-dortgenler',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Özel Dörtgenler: Paralelkenar, Eşkenar Dörtgen, Yamuk',
              slug: 'ozel-dortgenler-paralelkenar-eskenar-dortgen-yamuk',
              orderIndex: 1,
              estimatedMinutes: 60,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Çember ve Daire',
              slug: 'cember-ve-daire',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Katı Cisimler: Prizma, Piramit, Küre',
              slug: 'kati-cisimler-prizma-piramit-kure',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.4,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Analitik Geometri: Nokta ve Doğru',
              slug: 'analitik-geometri-nokta-ve-dogru',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // TARİH — 27 soru
    // =====================================================================
    {
      name: 'Tarih',
      slug: 'tarih',
      orderIndex: 2,
      color: '38 92% 50%',
      questionCount: 27,
      units: [
        {
          name: 'İslamiyet Öncesi Türk Tarihi',
          slug: 'islamiyet-oncesi-turk-tarihi',
          orderIndex: 0,
          topics: [
            {
              title: "Türklerin Anayurdu ve Orta Asya'dan Göçler",
              slug: 'turklerin-anayurdu-ve-orta-asyadan-gocler',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İlk Türk Devletleri: Asya Hun, Göktürk ve Uygurlar',
              slug: 'ilk-turk-devletleri-asya-hun-gokturk-ve-uygurlar',
              orderIndex: 1,
              estimatedMinutes: 65,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Diğer Türk Devlet ve Toplulukları',
              slug: 'diger-turk-devlet-ve-topluluklari',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İslamiyet Öncesi Türklerde Kültür ve Medeniyet',
              slug: 'islamiyet-oncesi-turklerde-kultur-ve-medeniyet',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'İlk Türk-İslam Devletleri',
          slug: 'ilk-turk-islam-devletleri',
          orderIndex: 1,
          topics: [
            {
              title: "Türklerin İslamiyet'i Kabulü ve Talas Savaşı",
              slug: 'turklerin-islamiyeti-kabulu-ve-talas-savasi',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Tolunoğulları, Karahanlılar ve Gazneliler',
              slug: 'tolunogullari-karahanlilar-ve-gazneliler',
              orderIndex: 1,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Büyük Selçuklu Devleti',
              slug: 'buyuk-selcuklu-devleti',
              orderIndex: 2,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Türkiye Selçuklu Devleti ve Anadolu Beylikleri',
              slug: 'turkiye-selcuklu-devleti-ve-anadolu-beylikleri',
              orderIndex: 3,
              estimatedMinutes: 45,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Türk-İslam Devletlerinde Kültür ve Medeniyet',
              slug: 'turk-islam-devletlerinde-kultur-ve-medeniyet',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Osmanlı Devleti: Kuruluş ve Yükselme Dönemi',
          slug: 'osmanli-devleti-kurulus-ve-yukselme-donemi',
          orderIndex: 2,
          topics: [
            {
              title: "Osmanlı Devleti'nin Kuruluşu ve Beylikten Devlete Geçiş",
              slug: 'osmanli-devletinin-kurulusu-ve-beylikten-devlete-gecis',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Fetret Devri ve Toparlanma Süreci',
              slug: 'fetret-devri-ve-toparlanma-sureci',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "İstanbul'un Fethi ve Fatih Sultan Mehmet Dönemi",
              slug: 'istanbulun-fethi-ve-fatih-sultan-mehmet-donemi',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 2,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yavuz Sultan Selim Dönemi ve Doğu Seferleri',
              slug: 'yavuz-sultan-selim-donemi-ve-dogu-seferleri',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Kanuni Sultan Süleyman Dönemi',
              slug: 'kanuni-sultan-suleyman-donemi',
              orderIndex: 4,
              estimatedMinutes: 45,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Osmanlı Devleti: Duraklama ve Gerileme Dönemi',
          slug: 'osmanli-devleti-duraklama-ve-gerileme-donemi',
          orderIndex: 3,
          topics: [
            {
              title: 'Duraklama Dönemi Siyasi Olayları',
              slug: 'duraklama-donemi-siyasi-olaylari',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'XVII. Yüzyıl İç İsyanları ve Islahatları',
              slug: 'xvii-yuzyil-ic-isyanlari-ve-islahatlari',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Gerileme Dönemi ve Kaybedilen Topraklar',
              slug: 'gerileme-donemi-ve-kaybedilen-topraklar',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Lale Devri ve XVIII. Yüzyıl Islahatları',
              slug: 'lale-devri-ve-xviii-yuzyil-islahatlari',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'III. Selim ve II. Mahmut Dönemi Yenilikleri',
              slug: 'iii-selim-ve-ii-mahmut-donemi-yenilikleri',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Tanzimat, Islahat ve Meşrutiyet Dönemleri',
              slug: 'tanzimat-islahat-ve-mesrutiyet-donemleri',
              orderIndex: 5,
              estimatedMinutes: 65,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Osmanlı Kültür ve Medeniyeti',
          slug: 'osmanli-kultur-ve-medeniyeti',
          orderIndex: 4,
          topics: [
            {
              title: 'Osmanlı Devlet Yönetimi ve Merkez Teşkilatı',
              slug: 'osmanli-devlet-yonetimi-ve-merkez-teskilati',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Taşra Teşkilatı ve Toprak Sistemi',
              slug: 'tasra-teskilati-ve-toprak-sistemi',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Osmanlı Ordu Teşkilatı',
              slug: 'osmanli-ordu-teskilati',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Osmanlı'da Hukuk, Eğitim ve Maliye",
              slug: 'osmanlida-hukuk-egitim-ve-maliye',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Osmanlı'da Sosyal Hayat, Sanat ve Edebiyat",
              slug: 'osmanlida-sosyal-hayat-sanat-ve-edebiyat',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'XX. Yüzyıl Başlarında Osmanlı Devleti',
          slug: 'xx-yuzyil-baslarinda-osmanli-devleti',
          orderIndex: 5,
          topics: [
            {
              title: 'II. Meşrutiyet ve 31 Mart Olayı',
              slug: 'ii-mesrutiyet-ve-31-mart-olayi',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Trablusgarp ve Balkan Savaşları',
              slug: 'trablusgarp-ve-balkan-savaslari',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'I. Dünya Savaşı ve Osmanlı Cepheleri',
              slug: 'i-dunya-savasi-ve-osmanli-cepheleri',
              orderIndex: 2,
              estimatedMinutes: 75,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Gizli Antlaşmalar ve Mondros Ateşkes Antlaşması',
              slug: 'gizli-antlasmalar-ve-mondros-ateskes-antlasmasi',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Kurtuluş Savaşı',
          slug: 'kurtulus-savasi',
          orderIndex: 6,
          topics: [
            {
              title: 'İşgaller, Cemiyetler ve Millî Uyanış',
              slug: 'isgaller-cemiyetler-ve-milli-uyanis',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Kongreler Dönemi ve Genelgeler',
              slug: 'kongreler-donemi-ve-genelgeler',
              orderIndex: 1,
              estimatedMinutes: 65,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Misakımillî ve TBMM'nin Açılışı",
              slug: 'misakimilli-ve-tbmmnin-acilisi',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Doğu ve Güney Cepheleri',
              slug: 'dogu-ve-guney-cepheleri',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Batı Cephesi ve Düzenli Ordunun Kuruluşu',
              slug: 'bati-cephesi-ve-duzenli-ordunun-kurulusu',
              orderIndex: 4,
              estimatedMinutes: 70,
              difficulty: 4,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sakarya Meydan Muharebesi, Büyük Taarruz ve Mudanya',
              slug: 'sakarya-meydan-muharebesi-buyuk-taarruz-ve-mudanya',
              orderIndex: 5,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Lozan Barış Antlaşması',
              slug: 'lozan-baris-antlasmasi',
              orderIndex: 6,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Atatürk İlke ve İnkılapları',
          slug: 'ataturk-ilke-ve-inkilaplari',
          orderIndex: 7,
          topics: [
            {
              title: 'Siyasi Alanda Yapılan İnkılaplar',
              slug: 'siyasi-alanda-yapilan-inkilaplar',
              orderIndex: 0,
              estimatedMinutes: 60,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Hukuk Alanında Yapılan İnkılaplar',
              slug: 'hukuk-alaninda-yapilan-inkilaplar',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Eğitim, Kültür ve Toplumsal Alanda İnkılaplar',
              slug: 'egitim-kultur-ve-toplumsal-alanda-inkilaplar',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Ekonomi Alanındaki Gelişmeler',
              slug: 'ekonomi-alanindaki-gelismeler',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Çok Partili Hayata Geçiş Denemeleri ve İsyanlar',
              slug: 'cok-partili-hayata-gecis-denemeleri-ve-isyanlar',
              orderIndex: 4,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Atatürk İlkeleri',
              slug: 'ataturk-ilkeleri',
              orderIndex: 5,
              estimatedMinutes: 60,
              difficulty: 2,
              examWeight: 0.9,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Atatürk Dönemi Türk Dış Politikası',
              slug: 'ataturk-donemi-turk-dis-politikasi',
              orderIndex: 6,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Çağdaş Türk ve Dünya Tarihi',
          slug: 'cagdas-turk-ve-dunya-tarihi',
          orderIndex: 8,
          topics: [
            {
              title: 'İki Savaş Arası Dönem ve II. Dünya Savaşı',
              slug: 'iki-savas-arasi-donem-ve-ii-dunya-savasi',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Soğuk Savaş Dönemi ve Türkiye',
              slug: 'soguk-savas-donemi-ve-turkiye',
              orderIndex: 1,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Çok Partili Dönem ve Siyasi Gelişmeler",
              slug: 'turkiyede-cok-partili-donem-ve-siyasi-gelismeler',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yumuşama Dönemi ve Kıbrıs Meselesi',
              slug: 'yumusama-donemi-ve-kibris-meselesi',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Küreselleşen Dünya ve Günümüz Türkiyesi',
              slug: 'kuresellesen-dunya-ve-gunumuz-turkiyesi',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // COĞRAFYA — 18 soru
    // =====================================================================
    {
      name: 'Coğrafya',
      slug: 'cografya',
      orderIndex: 3,
      color: '142 71% 45%',
      questionCount: 18,
      units: [
        {
          name: "Türkiye'nin Coğrafi Konumu",
          slug: 'turkiyenin-cografi-konumu',
          orderIndex: 0,
          topics: [
            {
              title: 'Matematik Konum ve Sonuçları',
              slug: 'matematik-konum-ve-sonuclari',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Özel Konum ve Sonuçları',
              slug: 'ozel-konum-ve-sonuclari',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Sınırları ve Komşuları",
              slug: 'turkiyenin-sinirlari-ve-komsulari',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Harita Bilgisi ve Ölçek',
              slug: 'harita-bilgisi-ve-olcek',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'nin Yer Şekilleri",
          slug: 'turkiyenin-yer-sekilleri',
          orderIndex: 1,
          topics: [
            {
              title: "Türkiye'nin Jeolojik Yapısı ve Oluşumu",
              slug: 'turkiyenin-jeolojik-yapisi-ve-olusumu',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Dağlar, Ovalar ve Platolar',
              slug: 'daglar-ovalar-ve-platolar',
              orderIndex: 1,
              estimatedMinutes: 50,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Akarsuları ve Gölleri",
              slug: 'turkiyenin-akarsulari-ve-golleri',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Dış Kuvvetler ve Kıyı Tipleri',
              slug: 'dis-kuvvetler-ve-kiyi-tipleri',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 4,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yer Şekillerinin Beşerî Faaliyetlere Etkisi',
              slug: 'yer-sekillerinin-beseri-faaliyetlere-etkisi',
              orderIndex: 4,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'nin İklimi ve Bitki Örtüsü",
          slug: 'turkiyenin-iklimi-ve-bitki-ortusu',
          orderIndex: 2,
          topics: [
            {
              title: "Türkiye'nin İklimini Etkileyen Faktörler",
              slug: 'turkiyenin-iklimini-etkileyen-faktorler',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Görülen İklim Tipleri",
              slug: 'turkiyede-gorulen-iklim-tipleri',
              orderIndex: 1,
              estimatedMinutes: 60,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sıcaklık, Basınç ve Rüzgârlar',
              slug: 'sicaklik-basinc-ve-ruzgarlar',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yağış Rejimleri ve Yağışın Dağılışı',
              slug: 'yagis-rejimleri-ve-yagisin-dagilisi',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Doğal Bitki Örtüsü",
              slug: 'turkiyenin-dogal-bitki-ortusu',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'de Nüfus ve Yerleşme",
          slug: 'turkiyede-nufus-ve-yerlesme',
          orderIndex: 3,
          topics: [
            {
              title: 'Nüfusun Dağılışı ve Etkileyen Faktörler',
              slug: 'nufusun-dagilisi-ve-etkileyen-faktorler',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Nüfusun Yapısal Özellikleri ve Nüfus Piramitleri',
              slug: 'nufusun-yapisal-ozellikleri-ve-nufus-piramitleri',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Göçler ve Sonuçları',
              slug: 'gocler-ve-sonuclari',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Yerleşme Tipleri",
              slug: 'turkiyede-yerlesme-tipleri',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Şehirleşme ve Şehirlerin Fonksiyonları',
              slug: 'sehirlesme-ve-sehirlerin-fonksiyonlari',
              orderIndex: 4,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'de Tarım ve Hayvancılık",
          slug: 'turkiyede-tarim-ve-hayvancilik',
          orderIndex: 4,
          topics: [
            {
              title: 'Tarımı Etkileyen Faktörler ve Tarım Yöntemleri',
              slug: 'tarimi-etkileyen-faktorler-ve-tarim-yontemleri',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Tahıllar ve Endüstri Bitkileri',
              slug: 'tahillar-ve-endustri-bitkileri',
              orderIndex: 1,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Baklagiller, Meyve ve Sebze Üretimi',
              slug: 'baklagiller-meyve-ve-sebze-uretimi',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Hayvancılık",
              slug: 'turkiyede-hayvancilik',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Ormancılık ve Su Ürünleri',
              slug: 'ormancilik-ve-su-urunleri',
              orderIndex: 4,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'de Madenler ve Enerji Kaynakları",
          slug: 'turkiyede-madenler-ve-enerji-kaynaklari',
          orderIndex: 5,
          topics: [
            {
              title: "Türkiye'nin Maden Yatakları ve Dağılışı",
              slug: 'turkiyenin-maden-yataklari-ve-dagilisi',
              orderIndex: 0,
              estimatedMinutes: 60,
              difficulty: 4,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yenilenemeyen Enerji Kaynakları',
              slug: 'yenilenemeyen-enerji-kaynaklari',
              orderIndex: 1,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yenilenebilir Enerji Kaynakları',
              slug: 'yenilenebilir-enerji-kaynaklari',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Enerji Üretimi ve Tüketimi",
              slug: 'turkiyede-enerji-uretimi-ve-tuketimi',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'de Sanayi",
          slug: 'turkiyede-sanayi',
          orderIndex: 6,
          topics: [
            {
              title: 'Sanayinin Gelişimi ve Kuruluş Yeri Faktörleri',
              slug: 'sanayinin-gelisimi-ve-kurulus-yeri-faktorleri',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Başlıca Sanayi Kolları ve Merkezleri',
              slug: 'baslica-sanayi-kollari-ve-merkezleri',
              orderIndex: 1,
              estimatedMinutes: 50,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Organize Sanayi Bölgeleri ve Kalkınma Projeleri',
              slug: 'organize-sanayi-bolgeleri-ve-kalkinma-projeleri',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'de Ulaşım, Ticaret ve Turizm",
          slug: 'turkiyede-ulasim-ticaret-ve-turizm',
          orderIndex: 7,
          topics: [
            {
              title: "Türkiye'de Ulaşım Sistemleri",
              slug: 'turkiyede-ulasim-sistemleri',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de İç ve Dış Ticaret",
              slug: 'turkiyede-ic-ve-dis-ticaret',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'de Turizm ve Turizmin Ekonomiye Katkısı",
              slug: 'turkiyede-turizm-ve-turizmin-ekonomiye-katkisi',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 2,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin UNESCO Dünya Mirası Listesindeki Değerleri",
              slug: 'turkiyenin-unesco-dunya-mirasi-listesindeki-degerleri',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "Türkiye'nin Coğrafi Bölgeleri",
          slug: 'turkiyenin-cografi-bolgeleri',
          orderIndex: 8,
          topics: [
            {
              title: 'Karadeniz Bölgesi ve Marmara Bölgesi',
              slug: 'karadeniz-bolgesi-ve-marmara-bolgesi',
              orderIndex: 0,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Ege Bölgesi ve Akdeniz Bölgesi',
              slug: 'ege-bolgesi-ve-akdeniz-bolgesi',
              orderIndex: 1,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İç Anadolu Bölgesi',
              slug: 'ic-anadolu-bolgesi',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Doğu Anadolu ve Güneydoğu Anadolu Bölgeleri',
              slug: 'dogu-anadolu-ve-guneydogu-anadolu-bolgeleri',
              orderIndex: 3,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Bölümler, Yöreler ve Bölge Karşılaştırmaları',
              slug: 'bolumler-yoreler-ve-bolge-karsilastirmalari',
              orderIndex: 4,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // VATANDAŞLIK — 9 soru
    // =====================================================================
    {
      name: 'Vatandaşlık',
      slug: 'vatandaslik',
      orderIndex: 4,
      color: '271 76% 58%',
      questionCount: 9,
      units: [
        {
          name: 'Hukuk Başlangıcı',
          slug: 'hukuk-baslangici',
          orderIndex: 0,
          topics: [
            {
              title: 'Hukukun Tanımı, Kaynakları ve Dalları',
              slug: 'hukukun-tanimi-kaynaklari-ve-dallari',
              orderIndex: 0,
              estimatedMinutes: 45,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sosyal Düzen Kuralları ve Yaptırım Türleri',
              slug: 'sosyal-duzen-kurallari-ve-yaptirim-turleri',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Kişilik, Hak Ehliyeti ve Fiil Ehliyeti',
              slug: 'kisilik-hak-ehliyeti-ve-fiil-ehliyeti',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Devlet Kavramı, Unsurları ve Hükümet Sistemleri',
              slug: 'devlet-kavrami-unsurlari-ve-hukumet-sistemleri',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Anayasa Hukuku ve Türk Anayasa Tarihi',
          slug: 'anayasa-hukuku-ve-turk-anayasa-tarihi',
          orderIndex: 1,
          topics: [
            {
              title: 'Anayasa Kavramı ve Anayasa Türleri',
              slug: 'anayasa-kavrami-ve-anayasa-turleri',
              orderIndex: 0,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Osmanlı Dönemi Anayasal Gelişmeler',
              slug: 'osmanli-donemi-anayasal-gelismeler',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: '1921 ve 1924 Anayasaları',
              slug: '1921-ve-1924-anayasalari',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: '1961 ve 1982 Anayasaları',
              slug: '1961-ve-1982-anayasalari',
              orderIndex: 3,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: "1982 Anayasası'nın Genel Esasları",
          slug: '1982-anayasasinin-genel-esaslari',
          orderIndex: 2,
          topics: [
            {
              title: 'Cumhuriyetin Nitelikleri',
              slug: 'cumhuriyetin-nitelikleri',
              orderIndex: 0,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Devletin Temel Amaç ve Görevleri, Egemenlik',
              slug: 'devletin-temel-amac-ve-gorevleri-egemenlik',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Başlangıç İlkeleri ve Anayasanın Üstünlüğü',
              slug: 'baslangic-ilkeleri-ve-anayasanin-ustunlugu',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Anayasanın Değiştirilmesi ve Değiştirilemeyecek Hükümler',
              slug: 'anayasanin-degistirilmesi-ve-degistirilemeyecek-hukumler',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 4,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Temel Hak ve Ödevler',
          slug: 'temel-hak-ve-odevler',
          orderIndex: 3,
          topics: [
            {
              title: 'Temel Hak ve Hürriyetlerin Niteliği ve Sınırlandırılması',
              slug: 'temel-hak-ve-hurriyetlerin-niteligi-ve-sinirlandirilmasi',
              orderIndex: 0,
              estimatedMinutes: 45,
              difficulty: 4,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Kişinin Hakları ve Ödevleri',
              slug: 'kisinin-haklari-ve-odevleri',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sosyal ve Ekonomik Haklar ve Ödevler',
              slug: 'sosyal-ve-ekonomik-haklar-ve-odevler',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Siyasi Haklar ve Ödevler',
              slug: 'siyasi-haklar-ve-odevler',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Olağanüstü Hâllerde Temel Hakların Sınırlandırılması',
              slug: 'olaganustu-hallerde-temel-haklarin-sinirlandirilmasi',
              orderIndex: 4,
              estimatedMinutes: 25,
              difficulty: 4,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Yasama',
          slug: 'yasama',
          orderIndex: 4,
          topics: [
            {
              title: "TBMM'nin Kuruluşu, Seçimler ve Milletvekilliği",
              slug: 'tbmmnin-kurulusu-secimler-ve-milletvekilligi',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "TBMM'nin Görev ve Yetkileri",
              slug: 'tbmmnin-gorev-ve-yetkileri',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.75,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yasama Dokunulmazlığı ve Yasama Sorumsuzluğu',
              slug: 'yasama-dokunulmazligi-ve-yasama-sorumsuzlugu',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "TBMM'nin Bilgi Edinme ve Denetim Yolları",
              slug: 'tbmmnin-bilgi-edinme-ve-denetim-yollari',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 4,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Yürütme',
          slug: 'yurutme',
          orderIndex: 5,
          topics: [
            {
              title: 'Cumhurbaşkanı: Seçimi, Görev ve Yetkileri',
              slug: 'cumhurbaskani-secimi-gorev-ve-yetkileri',
              orderIndex: 0,
              estimatedMinutes: 55,
              difficulty: 3,
              examWeight: 0.85,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cumhurbaşkanı Yardımcıları ve Bakanlar',
              slug: 'cumhurbaskani-yardimcilari-ve-bakanlar',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Cumhurbaşkanlığı Kararnamesi ve Düzenleyici İşlemler',
              slug: 'cumhurbaskanligi-kararnamesi-ve-duzenleyici-islemler',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Olağanüstü Hâl Yönetimi ve Millî Güvenlik Kurulu',
              slug: 'olaganustu-hal-yonetimi-ve-milli-guvenlik-kurulu',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Yargı',
          slug: 'yargi',
          orderIndex: 6,
          topics: [
            {
              title: 'Yargı Bağımsızlığı ve Hâkimlik Teminatı',
              slug: 'yargi-bagimsizligi-ve-hakimlik-teminati',
              orderIndex: 0,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Anayasa Mahkemesi',
              slug: 'anayasa-mahkemesi',
              orderIndex: 1,
              estimatedMinutes: 50,
              difficulty: 4,
              examWeight: 0.8,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Yüksek Mahkemeler ve Sayıştay',
              slug: 'yuksek-mahkemeler-ve-sayistay',
              orderIndex: 2,
              estimatedMinutes: 35,
              difficulty: 4,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Hâkimler ve Savcılar Kurulu',
              slug: 'hakimler-ve-savcilar-kurulu',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'İdare Hukuku',
          slug: 'idare-hukuku',
          orderIndex: 7,
          topics: [
            {
              title: 'İdarenin Kuruluşu: Merkezden ve Yerinden Yönetim',
              slug: 'idarenin-kurulusu-merkezden-ve-yerinden-yonetim',
              orderIndex: 0,
              estimatedMinutes: 35,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Merkezî İdare: Başkent ve Taşra Teşkilatı',
              slug: 'merkezi-idare-baskent-ve-tasra-teskilati',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Mahallî İdareler: Belediye, İl Özel İdaresi ve Köy',
              slug: 'mahalli-idareler-belediye-il-ozel-idaresi-ve-koy',
              orderIndex: 2,
              estimatedMinutes: 40,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'İdarenin Denetimi ve Kamu Denetçiliği Kurumu',
              slug: 'idarenin-denetimi-ve-kamu-denetciligi-kurumu',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Kamu Görevlileri ve Memur Hukuku',
              slug: 'kamu-gorevlileri-ve-memur-hukuku',
              orderIndex: 4,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Uluslararası Kuruluşlar',
          slug: 'uluslararasi-kuruluslar',
          orderIndex: 8,
          topics: [
            {
              title: 'Birleşmiş Milletler ve Uzmanlık Kuruluşları',
              slug: 'birlesmis-milletler-ve-uzmanlik-kuruluslari',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Avrupa Birliği ve Türkiye-AB İlişkileri',
              slug: 'avrupa-birligi-ve-turkiye-ab-iliskileri',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'NATO, AGİT ve Avrupa Konseyi',
              slug: 'nato-agit-ve-avrupa-konseyi',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Ekonomik ve Bölgesel İş Birliği Kuruluşları',
              slug: 'ekonomik-ve-bolgesel-is-birligi-kuruluslari',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Avrupa İnsan Hakları Mahkemesi ve Uluslararası Yargı Organları',
              slug: 'avrupa-insan-haklari-mahkemesi-ve-uluslararasi-yargi-organlari',
              orderIndex: 4,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // GÜNCEL BİLGİLER — 6 soru
    // =====================================================================
    {
      name: 'Güncel Bilgiler',
      slug: 'guncel-bilgiler',
      orderIndex: 5,
      color: '190 85% 45%',
      questionCount: 6,
      units: [
        {
          name: 'Türkiye ve Dünya Kuruluşları',
          slug: 'turkiye-ve-dunya-kuruluslari',
          orderIndex: 0,
          topics: [
            {
              title: 'Uluslararası Kuruluşların Merkezleri ve Yöneticileri',
              slug: 'uluslararasi-kuruluslarin-merkezleri-ve-yoneticileri',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.7,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Üyesi Olduğu Kuruluşlar ve Dönem Başkanlıkları",
              slug: 'turkiyenin-uyesi-oldugu-kuruluslar-ve-donem-baskanliklari',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'deki Kamu Kurumları ve Düzenleyici Üst Kurullar",
              slug: 'turkiyedeki-kamu-kurumlari-ve-duzenleyici-ust-kurullar',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Zirveler, Konferanslar ve Uluslararası Anlaşmalar',
              slug: 'zirveler-konferanslar-ve-uluslararasi-anlasmalar',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Ödüller, Kültür ve Sanat',
          slug: 'oduller-kultur-ve-sanat',
          orderIndex: 1,
          topics: [
            {
              title: 'Nobel Ödülleri ve Bilim Ödülleri',
              slug: 'nobel-odulleri-ve-bilim-odulleri',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Sinema Ödülleri ve Film Festivalleri',
              slug: 'sinema-odulleri-ve-film-festivalleri',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Edebiyat Ödülleri ve Güncel Türk Edebiyatı',
              slug: 'edebiyat-odulleri-ve-guncel-turk-edebiyati',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'UNESCO Dünya Mirası ve Kültür Başkentleri',
              slug: 'unesco-dunya-mirasi-ve-kultur-baskentleri',
              orderIndex: 3,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Spor Organizasyonları',
          slug: 'spor-organizasyonlari',
          orderIndex: 2,
          topics: [
            {
              title: 'Olimpiyat ve Paralimpik Oyunlar',
              slug: 'olimpiyat-ve-paralimpik-oyunlar',
              orderIndex: 0,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Dünya ve Avrupa Şampiyonaları',
              slug: 'dunya-ve-avrupa-sampiyonalari',
              orderIndex: 1,
              estimatedMinutes: 25,
              difficulty: 2,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Türk Sporcuların Uluslararası Başarıları',
              slug: 'turk-sporcularin-uluslararasi-basarilari',
              orderIndex: 2,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.45,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Ev Sahipliği Yaptığı Spor Organizasyonları",
              slug: 'turkiyenin-ev-sahipligi-yaptigi-spor-organizasyonlari',
              orderIndex: 3,
              estimatedMinutes: 20,
              difficulty: 2,
              examWeight: 0.4,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
        {
          name: 'Ekonomi ve Teknoloji Gündemi',
          slug: 'ekonomi-ve-teknoloji-gundemi',
          orderIndex: 3,
          topics: [
            {
              title: 'Temel Ekonomik Kavramlar ve Göstergeler',
              slug: 'temel-ekonomik-kavramlar-ve-gostergeler',
              orderIndex: 0,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.6,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: "Türkiye'nin Dış Ticareti ve Büyük Yatırım Projeleri",
              slug: 'turkiyenin-dis-ticareti-ve-buyuk-yatirim-projeleri',
              orderIndex: 1,
              estimatedMinutes: 30,
              difficulty: 3,
              examWeight: 0.55,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Savunma Sanayii ve Yerli Teknoloji Projeleri',
              slug: 'savunma-sanayii-ve-yerli-teknoloji-projeleri',
              orderIndex: 2,
              estimatedMinutes: 30,
              difficulty: 2,
              examWeight: 0.65,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
            {
              title: 'Uzay, Enerji ve Dijital Dönüşüm Gündemi',
              slug: 'uzay-enerji-ve-dijital-donusum-gundemi',
              orderIndex: 3,
              estimatedMinutes: 25,
              difficulty: 3,
              examWeight: 0.5,
              memoryNote: '',
              outcomes: [],
              videos: [],
              questions: [],
              flashcards: [],
            },
          ],
        },
      ],
    },
  ],
}
