import type { ReactNode } from 'react'
import { Badge } from '@zihin/ui/badge'
import { section } from '@/lib/i18n'
import type { CardStrings } from './strings'

/**
 * Konuya göre gözatma listesi.
 *
 * Cevap `<details>` ile açılır: durum tarayıcıdadır, bu yüzden liste sunucu
 * bileşeni olarak kalabiliyor ve iki yüzü de sunucuda basılmış Markdown
 * düğümleri taşıyor.
 */

export type CardListItem = {
  flashcardId: string
  front: ReactNode
  back: ReactNode
  autoGenerated: boolean
}

export function CardList({
  title,
  hint,
  items,
  emptyText,
}: {
  title: string
  hint: string
  items: CardListItem[]
  emptyText: string
}) {
  const s = section<CardStrings>('cards')

  return (
    <section className="space-y-3">
      <div className="space-y-1">
        <h2 className="text-foreground text-base font-semibold">{title}</h2>
        <p className="text-muted-foreground text-sm">{hint}</p>
      </div>

      {items.length === 0 ? (
        <p className="border-border text-muted-foreground rounded-lg border border-dashed px-4 py-8 text-center text-sm">
          {emptyText}
        </p>
      ) : (
        <ul className="space-y-2">
          {items.map((item) => (
            <li key={item.flashcardId} className="border-border bg-card rounded-lg border p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">{item.front}</div>
                {item.autoGenerated ? (
                  <Badge variant="secondary" className="shrink-0 text-xs">
                    {s.autoBadge}
                  </Badge>
                ) : null}
              </div>
              <details className="mt-2">
                <summary className="text-primary cursor-pointer text-sm font-medium">
                  {s.showAnswer}
                </summary>
                <div className="border-border mt-2 border-t pt-2">{item.back}</div>
              </details>
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}
