'use client'

import * as React from 'react'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { CheckCircle2, Loader2, RotateCw } from 'lucide-react'
import { Badge } from '@zihin/ui/badge'
import { Button } from '@zihin/ui/button'
import { Progress } from '@zihin/ui/progress'
import { cn } from '@zihin/ui/lib/utils'
import { reviewCard } from '@/app/(student)/kartlar/actions'
import { REVIEW_GRADES, gradeForKeyboardDigit } from '@/lib/cards/queue'
import { fill, section } from '@/lib/i18n/cards'
import type { CardStrings } from './strings'

/**
 * "Bugün Tekrar" akışı (spec §9.11).
 *
 * Kartın iki yüzü SUNUCUDA basılmış React düğümleri olarak gelir; Markdown +
 * KaTeX yığını bu istemci paketine girmez (Faz 3'te 127 kB'lık aynı hata
 * yapılıp geri alınmıştı).
 *
 * Çevirme animasyonu `app/globals.css` içindeki `.flip-card` ailesini kullanır;
 * burada ikinci bir animasyon tanımlanmaz.
 */

export type ReviewCardItem = {
  flashcardId: string
  front: React.ReactNode
  back: React.ReactNode
  imageUrl: string | null
  topicLabel: string | null
  autoGenerated: boolean
}

type ReviewSessionProps = {
  cards: ReviewCardItem[]
  /** Kotaya kırpılmadan önce vadesi gelmiş toplam kart sayısı. */
  dueTotal: number
}

type GradeButton = {
  grade: (typeof REVIEW_GRADES)[keyof typeof REVIEW_GRADES]
  label: string
  hint: string
  shortcut: string
  variant: React.ComponentProps<typeof Button>['variant']
}

export function ReviewSession({ cards, dueTotal }: ReviewSessionProps) {
  const s = section<CardStrings>('cards')
  const router = useRouter()

  const [index, setIndex] = React.useState(0)
  const [flipped, setFlipped] = React.useState(false)
  const [pending, setPending] = React.useState(false)
  const [earnedXp, setEarnedXp] = React.useState(0)
  const [reviewedCount, setReviewedCount] = React.useState(0)
  const [announcement, setAnnouncement] = React.useState('')

  const current = cards[index]
  const finished = current === undefined

  const buttons: GradeButton[] = [
    {
      grade: REVIEW_GRADES.again,
      label: s.gradeAgain,
      hint: s.gradeAgainHint,
      shortcut: '1',
      variant: 'destructive',
    },
    {
      grade: REVIEW_GRADES.hard,
      label: s.gradeHard,
      hint: s.gradeHardHint,
      shortcut: '2',
      variant: 'outline',
    },
    {
      grade: REVIEW_GRADES.good,
      label: s.gradeGood,
      hint: s.gradeGoodHint,
      shortcut: '3',
      variant: 'secondary',
    },
    {
      grade: REVIEW_GRADES.easy,
      label: s.gradeEasy,
      hint: s.gradeEasyHint,
      shortcut: '4',
      variant: 'default',
    },
  ]

  const labelForGrade = React.useCallback(
    (value: number) => buttons.find((button) => button.grade === value)?.label ?? '',
    // `buttons` her render'da yeniden kuruluyor ama içeriği sözlükten geldiği
    // için sabittir; bağımlılık listesi bilerek boş bırakılmadı.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [s],
  )

  const grade = React.useCallback(
    async (value: number) => {
      if (pending || current === undefined) return
      setPending(true)
      try {
        const result = await reviewCard({ flashcardId: current.flashcardId, grade: value })
        if (!result.ok) {
          toast.error(result.error.message)
          return
        }
        setEarnedXp((previous) => previous + result.data.awardedXp)
        setReviewedCount((previous) => previous + 1)
        // Puanlamanın sonucu GÖRSEL DEĞİL: kart kayboluyor, yerine yenisi
        // geliyor ve ekran okuyucu kullanan biri ne olduğunu anlamıyordu.
        // Sonuç canlı bölgeye yazılır (CONVENTIONS §8).
        setAnnouncement(
          fill(s.gradeAnnouncement, {
            label: labelForGrade(value),
            days: result.data.intervalDays,
            xp: result.data.awardedXp,
          }),
        )
        setFlipped(false)
        setIndex((previous) => previous + 1)
      } catch {
        toast.error(s.saveFailed)
      } finally {
        setPending(false)
      }
    },
    [current, labelForGrade, pending, s.gradeAnnouncement, s.saveFailed],
  )

  // Klavye: boşluk çevirir, 1-4 puanlar. Bir form alanına yazarken devre dışı.
  React.useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (finished) return
      const target = event.target
      if (target instanceof HTMLElement) {
        const tag = target.tagName
        if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || target.isContentEditable) {
          return
        }
      }

      if (event.key === ' ' || event.key === 'Spacebar') {
        // Sayfayı kaydırmasın; boşluk burada bir eylem tuşudur.
        event.preventDefault()
        setFlipped((previous) => !previous)
        return
      }

      if (!flipped) return
      const value = gradeForKeyboardDigit(event.key)
      if (value === null) return
      event.preventDefault()
      void grade(value)
    }

    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [finished, flipped, grade])

  if (finished) {
    const remaining = Math.max(0, dueTotal - reviewedCount)
    return (
      <div className="border-border flex flex-col items-center gap-3 rounded-lg border p-8 text-center">
        <CheckCircle2 aria-hidden="true" className="text-mastery-strong size-10" />
        <h3 className="text-foreground text-lg font-semibold">{s.doneTitle}</h3>
        <p className="text-muted-foreground text-sm">
          {fill(s.doneBody, { count: reviewedCount })}
        </p>
        <p className="text-foreground text-sm font-medium">{fill(s.doneXp, { xp: earnedXp })}</p>
        {remaining > 0 ? (
          <p className="text-muted-foreground text-sm">
            {fill(s.doneRemaining, { count: remaining })}
          </p>
        ) : null}
        <Button
          type="button"
          variant="outline"
          size="sm"
          className="mt-2"
          onClick={() => router.refresh()}
        >
          <RotateCw aria-hidden="true" className="size-4" />
          {s.reviewTitle}
        </Button>
      </div>
    )
  }

  const total = cards.length
  const position = index + 1

  return (
    <section className="space-y-4" aria-labelledby="tekrar-basligi">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 id="tekrar-basligi" className="text-foreground text-base font-semibold">
          {s.reviewTitle}
        </h2>
        <p className="text-muted-foreground text-sm tabular-nums" aria-live="polite">
          {fill(s.progress, { current: position, total })}
        </p>
      </div>

      <Progress value={(index / total) * 100} aria-label={s.reviewTitle} />

      <div className={cn('flip-card', flipped && 'is-flipped')}>
        <div className="flip-card-inner grid min-h-64">
          <CardFace
            className="col-start-1 row-start-1"
            hidden={flipped}
            label={s.front}
            badge={current.autoGenerated ? s.autoBadge : null}
            topicLabel={current.topicLabel}
            imageUrl={current.imageUrl}
            imageAlt={s.cardImage}
          >
            {current.front}
          </CardFace>
          <CardFace
            className="flip-face-back col-start-1 row-start-1"
            hidden={!flipped}
            label={s.back}
            badge={null}
            topicLabel={current.topicLabel}
            imageUrl={null}
            imageAlt={s.cardImage}
          >
            {current.back}
          </CardFace>
        </div>
      </div>

      {flipped ? (
        <div className="space-y-2">
          <p className="text-muted-foreground text-sm">{s.gradeQuestion}</p>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            {buttons.map((button) => (
              <Button
                key={button.grade}
                type="button"
                variant={button.variant}
                disabled={pending}
                aria-busy={pending}
                title={button.hint}
                onClick={() => void grade(button.grade)}
              >
                {pending ? <Loader2 aria-hidden="true" className="size-4 animate-spin" /> : null}
                {button.label}
                <span className="text-xs tabular-nums opacity-70">{`(${button.shortcut})`}</span>
              </Button>
            ))}
          </div>
        </div>
      ) : (
        <Button type="button" className="w-full sm:w-auto" onClick={() => setFlipped(true)}>
          {s.flip}
        </Button>
      )}

      <p className="text-muted-foreground text-xs">{s.keyboardHint}</p>

      {/* Puanlama sonucunun tek sesli karşılığı. Boşken de DOM'da durur:
          sonradan eklenen bir canlı bölge okunmaz. */}
      <p aria-live="polite" role="status" className="sr-only">
        {announcement}
      </p>
    </section>
  )
}

type CardFaceProps = {
  children: React.ReactNode
  label: string
  badge: string | null
  topicLabel: string | null
  imageUrl: string | null
  imageAlt: string
  hidden: boolean
  className?: string
}

/**
 * Kartın bir yüzü. İki yüz aynı ızgara gözünde üst üste durur; görünürlüğü
 * `backface-visibility` halleder. Görünmeyen yüz ekran okuyucudan da gizlenir,
 * aksi hâlde iki metin arka arkaya okunurdu.
 */
function CardFace({
  children,
  label,
  badge,
  topicLabel,
  imageUrl,
  imageAlt,
  hidden,
  className,
}: CardFaceProps) {
  return (
    <div
      aria-hidden={hidden}
      className={cn(
        'flip-face border-border bg-card text-card-foreground flex flex-col gap-3 overflow-y-auto rounded-lg border p-5 shadow-sm',
        className,
      )}
    >
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-muted-foreground text-xs uppercase tracking-wide">{label}</span>
        {badge ? (
          <Badge variant="secondary" className="text-xs">
            {badge}
          </Badge>
        ) : null}
        {topicLabel ? <span className="text-muted-foreground text-xs">· {topicLabel}</span> : null}
      </div>

      <div className="min-w-0 flex-1">{children}</div>

      {imageUrl ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={imageUrl} alt={imageAlt} className="h-auto max-h-48 w-auto rounded-md" />
      ) : null}
    </div>
  )
}
