/**
 * Tekrar destesinin saf mantığı.
 *
 * Burada Supabase, React ve `server-only` yoktur: dosya hem sunucu veri
 * katmanından hem de birim testlerinden okunur. SM-2 matematiği `@zihin/core`
 * içindedir ve burada YENİDEN YAZILMAZ; bu dosya yalnızca veritabanı
 * satırlarını core'un beklediği `CardState` biçimine çevirir ve `selectDueCards`
 * ile deste kurar.
 */

import { initialCardState, selectDueCards, type CardState, type ReviewGrade } from '@zihin/core'

/**
 * Günlük tekrar kotası (spec §M9). Ürün kararıdır, algoritmanın parçası
 * değildir: `buildReviewQueue` çağrısına farklı bir limit geçerek
 * değiştirilebilir (ileride kullanıcı ayarı olması planlanıyor).
 *
 * Core da aynı sayıyı `DEFAULT_DAILY_REVIEW_LIMIT` olarak taşır; burada
 * yeniden yazılmasının sebebi arayüz metinlerinin ve sorgu limitlerinin bu
 * sabite ada dayalı olarak bakabilmesi.
 */
export const DAILY_REVIEW_LIMIT = 50

/**
 * Arayüzdeki dört düğmenin SM-2 karşılığı (spec §9.11).
 * `ReviewGrade` 0-5 aralığındadır; kullanıcıya yalnızca bu dördü sunulur.
 */
export const REVIEW_GRADES = {
  again: 1,
  hard: 3,
  good: 4,
  easy: 5,
} as const satisfies Record<string, ReviewGrade>

export type ReviewGradeKey = keyof typeof REVIEW_GRADES

/** Düğme sırası — klavye kısayolu 1-4 bu sırayı izler. */
export const REVIEW_GRADE_ORDER: readonly ReviewGradeKey[] = ['again', 'hard', 'good', 'easy']

/**
 * İstemciden gelen sayıyı SM-2 puanına çevirir.
 *
 * Server Action herkese açık bir uçtur: 2 ya da 4.5 gibi arayüzde hiç
 * bulunmayan bir değer de gönderilebilir. Kabul edilen tek küme dört düğmenin
 * değerleridir; geri kalanı `null` döner ve çağıran reddeder.
 */
export function toReviewGrade(value: unknown): ReviewGrade | null {
  if (typeof value !== 'number' || !Number.isInteger(value)) return null
  for (const key of REVIEW_GRADE_ORDER) {
    if (REVIEW_GRADES[key] === value) return REVIEW_GRADES[key]
  }
  return null
}

/** Klavyedeki 1-4 tuşunu puana çevirir. Başka tuş `null` döner. */
export function gradeForKeyboardDigit(digit: string): ReviewGrade | null {
  const index = Number.parseInt(digit, 10) - 1
  const key = REVIEW_GRADE_ORDER[index]
  return key === undefined ? null : REVIEW_GRADES[key]
}

/** `card_reviews` satırının tekrar hesabı için gereken alanları. */
export type CardReviewSnapshot = {
  easeFactor: number
  intervalDays: number
  repetitions: number
  /** ISO zaman damgası. */
  nextReviewAt: string
  lastGrade: number | null
}

/** Destede yer alabilecek kart. `review` null ise kart hiç çalışılmamıştır. */
export type QueueCandidate = {
  flashcardId: string
  topicId: string
  front: string
  back: string
  imageUrl: string | null
  autoGenerated: boolean
  /** Kartın oluşturulma anı; hiç çalışılmamış kartların sıra ölçütü. */
  createdAt: string
  review: CardReviewSnapshot | null
}

/**
 * Bozuk/eksik tarihte `new Date(...)` NaN üretir; NaN her karşılaştırmada
 * `false` döndüğü için kart sessizce desteden düşerdi. Çözülemeyen tarih
 * "şimdi" kabul edilir: kart gösterilir, sırası en sona düşmez.
 */
function parseDate(value: string, fallback: Date): Date {
  const parsed = new Date(value)
  return Number.isNaN(parsed.getTime()) ? new Date(fallback.getTime()) : parsed
}

/**
 * Kartın SM-2 durumunu üretir.
 *
 * Hiç çalışılmamış kart için core'un `initialCardState` çıktısı kullanılır ama
 * `nextReviewAt` kartın OLUŞTURULMA anına çekilir: yeni kart hemen
 * çalışılabilir olmalı (bkz. 0006_planning.sql, `next_review_at` yorumu) ve
 * "en eski önce" sıralaması yeni kartlar arasında da anlamlı kalmalı.
 */
export function toCardState(candidate: QueueCandidate, now: Date): CardState {
  return toCardStateFromReview(candidate.review, candidate.createdAt, now)
}

/**
 * Kartın SM-2 durumu, satırdan doğrudan.
 *
 * `fallbackDue`, tekrar satırı hiç yokken kullanılacak vade (kartın oluşturulma
 * anı). Server Action tarafı tek kart için bunu kullanır; deste tarafı
 * `toCardState` üzerinden aynı yere iner.
 */
export function toCardStateFromReview(
  review: CardReviewSnapshot | null,
  fallbackDue: string,
  now: Date,
): CardState {
  if (!review) {
    const base = initialCardState(now)
    return { ...base, nextReviewAt: parseDate(fallbackDue, now) }
  }

  return {
    easeFactor: review.easeFactor,
    intervalDays: review.intervalDays,
    repetitions: review.repetitions,
    nextReviewAt: parseDate(review.nextReviewAt, now),
    lastGrade: (review.lastGrade ?? null) as CardState['lastGrade'],
  }
}

/**
 * Bu tekrar PUAN ve günlük sayaç HAK EDİYOR MU?
 *
 * Kural: yalnızca vadesi GERÇEKTEN gelmiş kart ödüllendirilir. `reviewCard`
 * herkese açık bir uçtur; kural olmasaydı aynı kart döngüye alınıp her
 * çağrıda 1 XP toplanabilir ve "bugün 15 dakika çalıştım" eşiği uydurulabilirdi
 * (Faz 3'te `completeVideo` tam olarak bu hatayı yapmıştı).
 *
 * Puanlanan kartın vadesi SM-2 tarafından geleceğe atıldığı için ikinci çağrı
 * kendiliğinden ödülsüz kalır. Kart yine de puanlanır — öğrenci istediği kartı
 * erken çalışabilmeli, sadece bunun için puan almaz.
 */
export function isRewardableReview(nextReviewAt: Date, now: Date): boolean {
  return nextReviewAt.getTime() <= now.getTime()
}

export type QueuedCard = QueueCandidate & { state: CardState }

/**
 * Zamanı gelmiş kartları en eskiden yeniye sıralar ve günlük kotaya kırpar.
 *
 * Sıralama ve kırpma core'un `selectDueCards` fonksiyonundadır (eşit tarihlerde
 * girdi sırası korunur); burada yalnızca durum dönüşümü yapılır.
 */
export function buildReviewQueue(
  candidates: readonly QueueCandidate[],
  now: Date,
  limit: number = DAILY_REVIEW_LIMIT,
): QueuedCard[] {
  const withState: QueuedCard[] = candidates.map((candidate) => ({
    ...candidate,
    state: toCardState(candidate, now),
  }))

  return selectDueCards(withState, now, limit)
}
