import { describe, expect, it } from 'vitest'
import {
  DAILY_REVIEW_LIMIT,
  buildReviewQueue,
  gradeForKeyboardDigit,
  toCardState,
  toReviewGrade,
  isRewardableReview,
  type QueueCandidate,
} from './queue'

/**
 * SM-2 matematiği `packages/core` içinde test edilmiştir; burada YALNIZCA
 * deste seçimi (kota, sıralama, vade sınırı) ve puan eşlemesi doğrulanır.
 */

const NOW = new Date('2026-09-09T09:00:00.000Z')

function candidate(overrides: Partial<QueueCandidate> & { flashcardId: string }): QueueCandidate {
  return {
    topicId: 'topic-1',
    front: 'ön',
    back: 'arka',
    imageUrl: null,
    autoGenerated: false,
    createdAt: '2026-01-01T00:00:00.000Z',
    review: null,
    ...overrides,
  }
}

function reviewed(id: string, nextReviewAt: string): QueueCandidate {
  return candidate({
    flashcardId: id,
    review: {
      easeFactor: 2.5,
      intervalDays: 3,
      repetitions: 2,
      nextReviewAt,
      lastGrade: 4,
    },
  })
}

describe('toReviewGrade', () => {
  it('yalnızca dört düğmenin değerlerini kabul eder', () => {
    expect(toReviewGrade(1)).toBe(1)
    expect(toReviewGrade(3)).toBe(3)
    expect(toReviewGrade(4)).toBe(4)
    expect(toReviewGrade(5)).toBe(5)
  })

  it('arayüzde bulunmayan ya da tip olarak geçersiz değerleri reddeder', () => {
    for (const value of [0, 2, 6, -1, 4.5, '4', null, undefined, Number.NaN]) {
      expect(toReviewGrade(value)).toBeNull()
    }
  })
})

describe('gradeForKeyboardDigit', () => {
  it('1-4 tuşlarını düğme sırasına göre eşler', () => {
    expect(gradeForKeyboardDigit('1')).toBe(1)
    expect(gradeForKeyboardDigit('2')).toBe(3)
    expect(gradeForKeyboardDigit('3')).toBe(4)
    expect(gradeForKeyboardDigit('4')).toBe(5)
  })

  it('kapsam dışı tuşları yok sayar', () => {
    expect(gradeForKeyboardDigit('0')).toBeNull()
    expect(gradeForKeyboardDigit('5')).toBeNull()
    expect(gradeForKeyboardDigit('a')).toBeNull()
  })
})

describe('toCardState', () => {
  it('hiç çalışılmamış kartı oluşturulma anına vadelendirir', () => {
    const state = toCardState(candidate({ flashcardId: 'a' }), NOW)
    expect(state.nextReviewAt.toISOString()).toBe('2026-01-01T00:00:00.000Z')
    expect(state.repetitions).toBe(0)
    expect(state.lastGrade).toBeNull()
  })

  it('bozuk tarihi "şimdi" kabul eder, kartı düşürmez', () => {
    const state = toCardState(candidate({ flashcardId: 'a', createdAt: 'bozuk' }), NOW)
    expect(state.nextReviewAt.getTime()).toBe(NOW.getTime())
  })

  it('mevcut tekrar satırını olduğu gibi taşır', () => {
    const state = toCardState(reviewed('a', '2026-09-08T00:00:00.000Z'), NOW)
    expect(state.easeFactor).toBe(2.5)
    expect(state.intervalDays).toBe(3)
    expect(state.nextReviewAt.toISOString()).toBe('2026-09-08T00:00:00.000Z')
  })
})

describe('buildReviewQueue', () => {
  it('vadesi gelmemiş kartları dışarıda bırakır', () => {
    const queue = buildReviewQueue(
      [
        reviewed('gelecek', '2026-09-10T09:00:00.000Z'),
        reviewed('gecmis', '2026-09-08T09:00:00.000Z'),
      ],
      NOW,
    )
    expect(queue.map((card) => card.flashcardId)).toEqual(['gecmis'])
  })

  it('vade sınırında (tam eşitlik) kartı desteye alır', () => {
    const queue = buildReviewQueue([reviewed('tam', NOW.toISOString())], NOW)
    expect(queue).toHaveLength(1)
  })

  it('en eski vadeden yeniye sıralar', () => {
    const queue = buildReviewQueue(
      [
        reviewed('orta', '2026-09-07T00:00:00.000Z'),
        reviewed('eski', '2026-09-01T00:00:00.000Z'),
        reviewed('yeni', '2026-09-09T08:00:00.000Z'),
      ],
      NOW,
    )
    expect(queue.map((card) => card.flashcardId)).toEqual(['eski', 'orta', 'yeni'])
  })

  it('eşit vadede girdi sırasını korur', () => {
    const stamp = '2026-09-08T00:00:00.000Z'
    const queue = buildReviewQueue([reviewed('b', stamp), reviewed('a', stamp)], NOW)
    expect(queue.map((card) => card.flashcardId)).toEqual(['b', 'a'])
  })

  it('hiç çalışılmamış kartları da desteye alır', () => {
    const queue = buildReviewQueue([candidate({ flashcardId: 'yeni-kart' })], NOW)
    expect(queue.map((card) => card.flashcardId)).toEqual(['yeni-kart'])
  })

  it('gelecekte oluşturulmuş bir kartı henüz göstermez', () => {
    const queue = buildReviewQueue(
      [candidate({ flashcardId: 'ileri', createdAt: '2026-12-01T00:00:00.000Z' })],
      NOW,
    )
    expect(queue).toHaveLength(0)
  })

  it('günlük kotayı aşmaz ve varsayılanı 50 karttır', () => {
    const many = Array.from({ length: DAILY_REVIEW_LIMIT + 10 }, (_, index) =>
      reviewed(`k${index}`, '2026-09-08T00:00:00.000Z'),
    )
    expect(buildReviewQueue(many, NOW)).toHaveLength(DAILY_REVIEW_LIMIT)
    expect(DAILY_REVIEW_LIMIT).toBe(50)
  })

  it('kota çağrı başına değiştirilebilir', () => {
    const many = Array.from({ length: 10 }, (_, index) =>
      reviewed(`k${index}`, '2026-09-08T00:00:00.000Z'),
    )
    expect(buildReviewQueue(many, NOW, 3)).toHaveLength(3)
    expect(buildReviewQueue(many, NOW, 0)).toHaveLength(0)
  })
})

describe('isRewardableReview', () => {
  const now = new Date('2025-03-10T09:00:00.000Z')

  it('vadesi geçmiş kart ödüllendirilir', () => {
    expect(isRewardableReview(new Date('2025-03-09T09:00:00.000Z'), now)).toBe(true)
  })

  it('tam vadesinde olan kart ödüllendirilir', () => {
    expect(isRewardableReview(new Date(now), now)).toBe(true)
  })

  it('vadesi gelmemiş kart ödüllendirilmez — XP musluğu kapalı', () => {
    expect(isRewardableReview(new Date('2025-03-10T09:00:01.000Z'), now)).toBe(false)
    expect(isRewardableReview(new Date('2025-03-13T09:00:00.000Z'), now)).toBe(false)
  })
})
