import 'server-only'

import { AppError } from '@/lib/errors'
import {
  DAILY_REVIEW_LIMIT,
  buildReviewQueue,
  type QueueCandidate,
  type QueuedCard,
} from '@/lib/cards/queue'
import type { DataClient } from './client'

/**
 * Hafıza kartı okumaları (spec §M9).
 *
 * Hepsi OTURUM istemcisiyle çalışır: `flashcards` üzerindeki RLS zaten iki
 * grubu ayırır — editör kartları herkese açık, `auto_generated` kartlar
 * yalnızca sahibine. Yine de sorgular `created_by` / `auto_generated`
 * filtrelerini açıkça yazar (CONVENTIONS §3: yetki iki kez denetlenir; ayrıca
 * sorgu okunduğunda hangi grubun istendiği görünür olsun).
 *
 * Düz sorgu kuralı geçerlidir: iç içe select yok, ilişkiler JavaScript
 * tarafında birleştirilir.
 */

type Client = DataClient

/**
 * Vadesi gelmiş kartlar için taranacak en fazla `card_reviews` satırı.
 * Kotanın katıdır: konu süzgeci uygulandığında bir kısmı elenebileceği için
 * kotadan fazlası okunur.
 */
const DUE_SCAN_MULTIPLIER = 4

/** Hiç çalışılmamış kartlardan taranacak en fazla satır. */
const NEW_SCAN_MULTIPLIER = 4

export type CardTopic = {
  topicId: string
  title: string
  slug: string
  orderIndex: number
  unitId: string
  unitName: string
  subjectId: string
  subjectName: string
  subjectOrderIndex: number
}

export type FlashcardItem = {
  flashcardId: string
  topicId: string
  front: string
  back: string
  imageUrl: string | null
  autoGenerated: boolean
  createdAt: string
}

export type ReviewQueue = {
  cards: QueuedCard[]
  /** Kotaya kırpılmadan önce vadesi gelmiş toplam kart sayısı. */
  dueTotal: number
}

/* ------------------------------------------------------------------------- *
 * Konu kapsamı
 * ------------------------------------------------------------------------- */

/**
 * Kullanıcının sınavındaki konular (ders → ünite → konu, üç düz sorgu).
 *
 * Kartlar konuya bağlıdır ama konunun sınavı ancak ders üzerinden bilinir;
 * `topics` tablosunda `exam_id` yoktur. Silinmiş ders/ünite/konu dışarıdadır:
 * müfredattan kaldırılmış bir konunun kartı bugünün destesine girmemeli.
 */
export async function getExamCardTopics(client: Client, examId: string): Promise<CardTopic[]> {
  const { data: subjects, error: subjectError } = await client
    .from('subjects')
    .select('id, name, order_index')
    .eq('exam_id', examId)
    .is('deleted_at', null)
    .order('order_index', { ascending: true })

  if (subjectError) throw new AppError('internal', 'Dersler yüklenemedi.')
  const subjectRows = subjects ?? []
  if (subjectRows.length === 0) return []

  const { data: units, error: unitError } = await client
    .from('units')
    .select('id, name, subject_id, order_index')
    .in(
      'subject_id',
      subjectRows.map((subject) => subject.id),
    )
    .is('deleted_at', null)
    .order('order_index', { ascending: true })

  if (unitError) throw new AppError('internal', 'Üniteler yüklenemedi.')
  const unitRows = units ?? []
  if (unitRows.length === 0) return []

  const { data: topics, error: topicError } = await client
    .from('topics')
    .select('id, title, slug, unit_id, order_index')
    .in(
      'unit_id',
      unitRows.map((unit) => unit.id),
    )
    .is('deleted_at', null)
    .order('order_index', { ascending: true })

  if (topicError) throw new AppError('internal', 'Konular yüklenemedi.')

  const subjectById = new Map(subjectRows.map((subject) => [subject.id, subject]))
  const unitById = new Map(unitRows.map((unit) => [unit.id, unit]))

  return (topics ?? []).flatMap((topic) => {
    const unit = unitById.get(topic.unit_id)
    const subject = unit ? subjectById.get(unit.subject_id) : undefined
    if (!unit || !subject) return []
    return [
      {
        topicId: topic.id,
        title: topic.title,
        slug: topic.slug,
        orderIndex: topic.order_index,
        unitId: unit.id,
        unitName: unit.name,
        subjectId: subject.id,
        subjectName: subject.name,
        subjectOrderIndex: subject.order_index,
      },
    ]
  })
}

/* ------------------------------------------------------------------------- *
 * Bugünün destesi
 * ------------------------------------------------------------------------- */

/**
 * "Bugün Tekrar" destesi.
 *
 * Dört düz sorgu, hepsi sınırlı:
 *   1. vadesi gelmiş `card_reviews` satırları (en eski önce),
 *   2. o satırların kartları (kapsam + yayın süzgeci burada uygulanır),
 *   3. kapsamdaki en eski kartlar (hiç çalışılmamış aday havuzu),
 *   4. o adayların halihazırda bir tekrar satırı olup olmadığı.
 *
 * Sıralama, vade sınırı ve kota `lib/cards/queue.ts` içindeki saf mantıkta
 * uygulanır; SQL yalnızca aday toplar. Böylece deste kuralları birim testiyle
 * kilitlenebiliyor.
 */
export async function getReviewQueue(
  client: Client,
  userId: string,
  options: { topicIds: readonly string[]; now?: Date; limit?: number } = { topicIds: [] },
): Promise<ReviewQueue> {
  const now = options.now ?? new Date()
  const limit = options.limit ?? DAILY_REVIEW_LIMIT
  const topicIds = [...options.topicIds]
  if (topicIds.length === 0 || limit <= 0) return { cards: [], dueTotal: 0 }

  const nowIso = now.toISOString()

  const { data: dueReviews, error: dueError } = await client
    .from('card_reviews')
    .select('flashcard_id, ease_factor, interval_days, repetitions, next_review_at, last_grade')
    .eq('user_id', userId)
    .lte('next_review_at', nowIso)
    .order('next_review_at', { ascending: true })
    .limit(limit * DUE_SCAN_MULTIPLIER)

  if (dueError) throw new AppError('internal', 'Tekrar destesi yüklenemedi.')
  const reviewRows = dueReviews ?? []

  const reviewById = new Map(reviewRows.map((row) => [row.flashcard_id, row]))

  const dueCards =
    reviewRows.length === 0
      ? []
      : await readCards(client, {
          topicIds,
          ids: reviewRows.map((row) => row.flashcard_id),
        })

  const newCandidates = await readCards(client, {
    topicIds,
    limit: limit * NEW_SCAN_MULTIPLIER,
    oldestFirst: true,
  })

  // Hiç çalışılmamış olanları ayıklamak için bu adayların tekrar satırlarına
  // bakılır; vadesi gelmemiş bir kart yeni sayılıp desteye girmemeli.
  const reviewedIds = await findReviewedFlashcardIds(
    client,
    userId,
    newCandidates.map((card) => card.flashcardId),
  )

  const candidates: QueueCandidate[] = [
    ...dueCards.map((card) => toCandidate(card, reviewById.get(card.flashcardId) ?? null)),
    ...newCandidates
      .filter((card) => !reviewedIds.has(card.flashcardId))
      .map((card) => toCandidate(card, null)),
  ]

  const cards = buildReviewQueue(candidates, now, limit)

  // Toplam, kotaya kırpılmadan önceki gerçek sayıdır; tamamlama ekranı
  // "yarına kalan" kart sayısını buradan söyler.
  const dueTotal = await countDueReviews(client, userId, nowIso)

  return { cards, dueTotal }
}

type ReviewRow = {
  flashcard_id: string
  ease_factor: number
  interval_days: number
  repetitions: number
  next_review_at: string
  last_grade: number | null
}

function toCandidate(card: FlashcardItem, review: ReviewRow | null): QueueCandidate {
  return {
    flashcardId: card.flashcardId,
    topicId: card.topicId,
    front: card.front,
    back: card.back,
    imageUrl: card.imageUrl,
    autoGenerated: card.autoGenerated,
    createdAt: card.createdAt,
    review: review
      ? {
          easeFactor: Number(review.ease_factor),
          intervalDays: review.interval_days,
          repetitions: review.repetitions,
          nextReviewAt: review.next_review_at,
          lastGrade: review.last_grade,
        }
      : null,
  }
}

/** Vadesi gelmiş kart sayısı (kotadan bağımsız). */
export async function countDueReviews(
  client: Client,
  userId: string,
  nowIso: string = new Date().toISOString(),
): Promise<number> {
  const { count, error } = await client
    .from('card_reviews')
    .select('flashcard_id', { count: 'exact', head: true })
    .eq('user_id', userId)
    .lte('next_review_at', nowIso)

  if (error) throw new AppError('internal', 'Tekrar sayısı okunamadı.')
  return count ?? 0
}

/** Verilen kartlardan hangilerinin tekrar satırı var? */
async function findReviewedFlashcardIds(
  client: Client,
  userId: string,
  flashcardIds: readonly string[],
): Promise<Set<string>> {
  if (flashcardIds.length === 0) return new Set()

  const { data, error } = await client
    .from('card_reviews')
    .select('flashcard_id')
    .eq('user_id', userId)
    .in('flashcard_id', [...flashcardIds])

  if (error) throw new AppError('internal', 'Tekrar geçmişi okunamadı.')
  return new Set((data ?? []).map((row) => row.flashcard_id))
}

/* ------------------------------------------------------------------------- *
 * Konuya göre gözatma
 * ------------------------------------------------------------------------- */

/** Editörlerin hazırladığı, tüm öğrencilere açık kartlar. */
export async function getEditorCardsForTopic(
  client: Client,
  topicId: string,
  limit = 100,
): Promise<FlashcardItem[]> {
  return readCards(client, { topicIds: [topicId], autoGenerated: false, limit, oldestFirst: true })
}

/** Kullanıcının yanlışlarından üretilmiş kişisel kartları. */
export async function getOwnCardsForTopic(
  client: Client,
  userId: string,
  topicId: string,
  limit = 100,
): Promise<FlashcardItem[]> {
  return readCards(client, {
    topicIds: [topicId],
    autoGenerated: true,
    createdBy: userId,
    limit,
    oldestFirst: false,
  })
}

/** Konu başına kart sayısı — konu seçicide "12 kart" etiketi için. */
export async function countCardsByTopic(
  client: Client,
  topicIds: readonly string[],
): Promise<Map<string, number>> {
  if (topicIds.length === 0) return new Map()

  const { data, error } = await client
    .from('flashcards')
    .select('topic_id')
    .in('topic_id', [...topicIds])
    .eq('is_published', true)
    .is('deleted_at', null)

  if (error) throw new AppError('internal', 'Hafıza kartları yüklenemedi.')

  const counts = new Map<string, number>()
  for (const row of data ?? []) {
    counts.set(row.topic_id, (counts.get(row.topic_id) ?? 0) + 1)
  }
  return counts
}

/**
 * Kartı çalışma/gözatma için okur.
 *
 * `is_published` ve `deleted_at` süzgeçleri her okumada uygulanır: yayından
 * kaldırılmış bir kart destede de listede de görünmemeli.
 */
async function readCards(
  client: Client,
  options: {
    topicIds: readonly string[]
    ids?: readonly string[]
    autoGenerated?: boolean
    createdBy?: string
    limit?: number
    oldestFirst?: boolean
  },
): Promise<FlashcardItem[]> {
  if (options.topicIds.length === 0) return []
  if (options.ids && options.ids.length === 0) return []

  let query = client
    .from('flashcards')
    .select('id, topic_id, front, back, image_url, auto_generated, created_at')
    .in('topic_id', [...options.topicIds])
    .eq('is_published', true)
    .is('deleted_at', null)

  if (options.ids) query = query.in('id', [...options.ids])
  if (options.autoGenerated !== undefined) query = query.eq('auto_generated', options.autoGenerated)
  if (options.createdBy !== undefined) query = query.eq('created_by', options.createdBy)

  query = query.order('created_at', { ascending: options.oldestFirst !== false })
  if (options.limit !== undefined) query = query.limit(options.limit)

  const { data, error } = await query
  if (error) throw new AppError('internal', 'Hafıza kartları yüklenemedi.')

  return (data ?? []).map((row) => ({
    flashcardId: row.id,
    topicId: row.topic_id,
    front: row.front,
    back: row.back,
    imageUrl: row.image_url,
    autoGenerated: row.auto_generated,
    createdAt: row.created_at,
  }))
}

/* ------------------------------------------------------------------------- *
 * Tek kart (Server Action tarafı)
 * ------------------------------------------------------------------------- */

export type ReviewableCard = { flashcardId: string; topicId: string }

/**
 * Kartın kullanıcı için gerçekten okunabilir olup olmadığını doğrular.
 *
 * Bu, `reviewCard` action'ının SAHİPLİK denetimidir: RLS başkasının kişisel
 * kartını zaten döndürmez, burada satır bulunamazsa istek reddedilir. Bir
 * Server Action herkese açık bir uçtur; istemcinin gönderdiği kimliğe
 * güvenilmez.
 */
export async function findReviewableCard(
  client: Client,
  flashcardId: string,
): Promise<ReviewableCard | null> {
  const { data, error } = await client
    .from('flashcards')
    .select('id, topic_id')
    .eq('id', flashcardId)
    .eq('is_published', true)
    .is('deleted_at', null)
    .maybeSingle()

  if (error) throw new AppError('internal', 'Kart okunamadı.')
  return data ? { flashcardId: data.id, topicId: data.topic_id } : null
}

/** Kullanıcının bu karta ait SM-2 satırı. Yoksa null. */
export async function getCardReview(
  client: Client,
  userId: string,
  flashcardId: string,
): Promise<ReviewRow | null> {
  const { data, error } = await client
    .from('card_reviews')
    .select('flashcard_id, ease_factor, interval_days, repetitions, next_review_at, last_grade')
    .eq('user_id', userId)
    .eq('flashcard_id', flashcardId)
    .maybeSingle()

  if (error) throw new AppError('internal', 'Tekrar geçmişi okunamadı.')
  return data ?? null
}

/** SM-2 sonucunu yazar. Satır yoksa açılır, varsa güncellenir. */
export async function upsertCardReview(
  client: Client,
  input: {
    userId: string
    flashcardId: string
    easeFactor: number
    intervalDays: number
    repetitions: number
    nextReviewAt: string
    lastGrade: number
    lastReviewedAt: string
  },
): Promise<void> {
  const { error } = await client.from('card_reviews').upsert(
    {
      user_id: input.userId,
      flashcard_id: input.flashcardId,
      // numeric(4,2): iki basamağa yuvarlanmazsa Postgres zaten yuvarlar,
      // ama o zaman bir sonraki hesap veritabanındaki değerle sürdüğü için
      // yuvarlama burada açıkça yapılır.
      ease_factor: Math.round(input.easeFactor * 100) / 100,
      interval_days: input.intervalDays,
      repetitions: input.repetitions,
      next_review_at: input.nextReviewAt,
      last_grade: input.lastGrade,
      last_reviewed_at: input.lastReviewedAt,
    },
    { onConflict: 'user_id,flashcard_id' },
  )

  if (error) throw new AppError('internal', 'Tekrar kaydedilemedi.')
}

export type { QueuedCard }
