import Link from 'next/link'
import { buttonVariants } from '@zihin/ui/button'
import { PageHeader } from '@/components/common/page-header'
import { EmptyState } from '@/components/common/empty-state'
import { Markdown } from '@/components/common/markdown'
import { CardList, type CardListItem } from '@/components/cards/card-list'
import { ReviewSession, type ReviewCardItem } from '@/components/cards/review-session'
import { TopicFilter, type TopicFilterOption } from '@/components/cards/topic-filter'
import type { CardStrings } from '@/components/cards/strings'
import { requireOnboardedStudent } from '@/lib/auth'
import { createSupabaseServerClient } from '@/lib/supabase/server'
import {
  countCardsByTopic,
  getEditorCardsForTopic,
  getExamCardTopics,
  getOwnCardsForTopic,
  getReviewQueue,
  type CardTopic,
  type FlashcardItem,
} from '@/lib/data/cards'
import { section } from '@/lib/i18n'

/**
 * Hafıza kartları (spec §9.11).
 *
 * İki bölüm: bugünün tekrar destesi ve konuya göre gözatma. Kartların iki yüzü
 * de BURADA, sunucuda Markdown olarak basılır ve hazır düğüm olarak istemci
 * bileşenine geçer — KaTeX ve temizleme şeması istemci paketine girmez.
 *
 * Yetki denetimi düzendedir (`(student)/layout.tsx`).
 */

export const dynamic = 'force-dynamic'

/** Gözatma listelerinde konu başına gösterilecek en fazla kart. */
const BROWSE_LIMIT = 100

type PageProps = {
  searchParams: Promise<Record<string, string | string[] | undefined>>
}

export default async function CardsPage({ searchParams }: PageProps) {
  const s = section<CardStrings>('cards')
  const user = await requireOnboardedStudent()
  const params = await searchParams

  if (!user.examId) {
    return (
      <div className="space-y-6">
        <PageHeader title={s.title} description={s.description} />
        <EmptyState
          title={s.noExamTitle}
          description={s.noExamBody}
          action={
            <Link href="/ayarlar" className={buttonVariants({ variant: 'outline' })}>
              {s.filterApply}
            </Link>
          }
        />
      </div>
    )
  }

  const supabase = await createSupabaseServerClient()
  const topics = await getExamCardTopics(supabase, user.examId)
  const topicById = new Map(topics.map((topic) => [topic.topicId, topic]))

  // Müfredat ekranı `?konu=<slug>` ile bağlanıyor; kimlikle gelen çağrılar da
  // (`?topic=<uuid>`) kabul edilir.
  const selected = resolveSelectedTopic(topics, params)

  const scopeTopicIds = selected ? [selected.topicId] : topics.map((topic) => topic.topicId)

  const queue = await getReviewQueue(supabase, user.id, { topicIds: scopeTopicIds })

  const cardCounts = await countCardsByTopic(
    supabase,
    topics.map((topic) => topic.topicId),
  )
  const filterOptions: TopicFilterOption[] = topics
    .filter((topic) => (cardCounts.get(topic.topicId) ?? 0) > 0)
    .map((topic) => ({
      slug: topic.slug,
      label: `${topic.subjectName} · ${topic.title}`,
      cardCount: cardCounts.get(topic.topicId) ?? 0,
    }))

  const reviewCards: ReviewCardItem[] = queue.cards.map((card) => ({
    flashcardId: card.flashcardId,
    front: <Markdown content={card.front} className="text-base" />,
    back: <Markdown content={card.back} className="text-base" />,
    imageUrl: card.imageUrl,
    topicLabel: topicById.get(card.topicId)?.title ?? null,
    autoGenerated: card.autoGenerated,
  }))

  const editorCards = selected
    ? await getEditorCardsForTopic(supabase, selected.topicId, BROWSE_LIMIT)
    : []
  const ownCards = selected
    ? await getOwnCardsForTopic(supabase, user.id, selected.topicId, BROWSE_LIMIT)
    : []

  return (
    <div className="space-y-8">
      <PageHeader
        title={s.title}
        description={selected ? `${selected.subjectName} · ${selected.title}` : s.description}
      />

      {reviewCards.length > 0 ? (
        <ReviewSession cards={reviewCards} dueTotal={queue.dueTotal} />
      ) : (
        <EmptyState title={s.emptyQueueTitle} description={s.emptyQueueBody} />
      )}

      <section className="space-y-3">
        <h2 className="text-foreground text-base font-semibold">{s.filterTitle}</h2>
        <TopicFilter options={filterOptions} selectedSlug={selected?.slug ?? null} />
      </section>

      {selected ? (
        <div className="space-y-8">
          <CardList
            title={s.editorCards}
            hint={s.editorCardsHint}
            items={toListItems(editorCards)}
            emptyText={s.editorCardsEmpty}
          />
          <CardList
            title={s.myCards}
            hint={s.myCardsHint}
            items={toListItems(ownCards)}
            emptyText={s.myCardsEmpty}
          />
        </div>
      ) : null}
    </div>
  )
}

function toListItems(cards: FlashcardItem[]): CardListItem[] {
  return cards.map((card) => ({
    flashcardId: card.flashcardId,
    front: <Markdown content={card.front} className="[&_p:last-child]:mb-0" />,
    back: <Markdown content={card.back} className="[&_p:last-child]:mb-0" />,
    autoGenerated: card.autoGenerated,
  }))
}

/** `?konu=<slug>` ya da `?topic=<uuid>` — ikisi de aynı konuyu seçer. */
function resolveSelectedTopic(
  topics: CardTopic[],
  params: Record<string, string | string[] | undefined>,
): CardTopic | null {
  const slug = firstValue(params.konu)
  if (slug) {
    return topics.find((topic) => topic.slug === slug) ?? null
  }

  const topicId = firstValue(params.topic)
  if (topicId) {
    return topics.find((topic) => topic.topicId === topicId) ?? null
  }

  return null
}

function firstValue(value: string | string[] | undefined): string | null {
  if (Array.isArray(value)) return value[0] ?? null
  return value ?? null
}
